version: '3'

services:
  laptop-crud-service:
    build: ./laptop-crud
    volumes: 
      - ./laptop-crud:/app
    ports: 
      - 3000:3000
    environment: 
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_USER: laptop
      DB_NAME: app-crud
    networks:
      - laptop-crud
    depends_on:
      - postgres
  postgres:
    image: postgres:12.3
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: laptop
      POSTGRES_DB: app-crud
    networks:
      - laptop-crud
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 80:80
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: laptop
      PGADMIN_DEFAULT_PASSWORD: laptop
    networks:
      - laptop-crud
networks:
  laptop-crud:
  
volumes:
  db-data: